### ISSUE TITLE
what could I be doing wrong?

### ISSUE THREAD

**Issue by stephensong** [clebert/webpack-koa-dev-middleware#1]
I couldn't get the koa-webpack-(dev|hot)-middleware stuff to work, nor could I work out what the problem there was.

So I thought I'd try yours in desperation.   Alas I can't even get to first base with it.  When I try to:

```
let wpd = require("webpack-koa-dev-middleware"); 
app.use(wpd(compiler, {noInfo: true, publicPath: '/' }));  // fails
```

the call to wpd( ...) fails with 

```
TypeError: wpd is not a function
```

Looking into it, I see that your package has already been webpack-ed.  I've not seen that before in any of the npm packages I've had occasion to look at, which by now has been quite a few.  Is that intentional?  Might it be the source of my problem?  

I've been going for literally months now constantly upgrading / replacing / removing one bit after another trying to get my previously working system up and running with Babel 6.  Complete, unmitigated disaster!  Wtf was I thinking?  I don't know ...

The last few days I finally seem to have got things working with Babel 6.4, but alas, not with hmr.
I'm almost ready to give up on hmr - again.  Heck, might even give Go a shot - gotta be better than all this.  Sorry to vent, but I am just so, so tired of it all.

**Comment by Cap32** [comment]
@stephensong 
Use `let wpd = require("webpack-koa-dev-middleware").default;`.

@clebert
See http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

**Comment by stephensong** [comment]
Many thanks.  I wish I had seen that article a couple of months ago.  I am surprised that I'd not found it before.
